version: '3.1'

services:

  db:
    image: postgres:14
    container_name: workspace_service_postgres_container
    restart: always
    ports:
      # Avoid using the same port as the dataset service
      - "5434:5432"
    command: ["postgres", "-c", "log_statement=all"]
    env_file: .env  # Needed for the healthcheck
    environment:
      POSTGRES_PASSWORD: "admin" # postgres admin password
    # volumes:
    #   - ./scripts/initdb:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: workspace_service_pgadmin4_container
    restart: always
    ports:
      - "8082:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
